from DataImporter.common.Database.Database import insert_stock, insert_news_source, DUMMY_SOURCE_STRING
from DataImporter.common.DataModel.Source import Source
from DataImporter.common.DataModel.Stock import Stock


def db_setup():
    print("try db setup...")
    insert_stock(Stock('Apple Inc.', 'AAPL'))
    insert_stock(Stock('Nvidia Corp', 'NVDA'))
    insert_stock(Stock('AMD', 'AMD'))
    insert_stock(Stock('Amazon.com Inc', 'AMZN'))
    insert_stock(Stock('Microsoft Corp', 'MSFT'))
    insert_stock(Stock('Meta Class A', 'META'))
    insert_stock(Stock('Alphabet Class A', 'GOOGL'))
    insert_stock(Stock('Alphabet Class C', 'GOOG'))
    insert_stock(Stock('Berkshire Hathaway', 'BRK-A'))
    insert_stock(Stock('Eli Lilly & Co', 'LLY'))
    insert_stock(Stock('Broadcom Inc.', 'AVGO'))
    insert_stock(Stock('Jpmorgan Chase & Co.', 'JPM'))
    insert_stock(Stock('Tesla, Inc.', 'TSLA'))
    insert_stock(Stock('Exxon Mobil Corp', 'XOM'))
    insert_stock(Stock('Unitedhealth Group', 'UNH'))
    insert_stock(Stock('Visa Inc.', 'V'))
    insert_stock(Stock('Procter & Gamble', 'PG'))
    insert_stock(Stock('Costco Wholesale', 'COST'))
    insert_stock(Stock('Mastercard Inc.', 'MA'))
    insert_stock(Stock('Johnson & Johnson', 'JNJ'))
    insert_stock(Stock('Merck & Co', 'MRK'))
    insert_stock(Stock('Home Depot, Inc.', 'HD'))
    insert_stock(Stock('Abbvie Inc.', 'ABBV'))
    insert_stock(Stock('Netflix Inc', 'NFLX'))
    insert_stock(Stock('Walmart Inc.', 'WMT'))
    insert_stock(Stock('Chevron Corp', 'CVX'))
    insert_stock(Stock('Bank of America Corp', 'BAC'))
    insert_stock(Stock('Coca-Cola Company', 'KO'))
    insert_stock(Stock('Adobe Inc.', 'ADBE'))
    insert_stock(Stock('Salesforce Inc.', 'CRM'))
    insert_stock(Stock('Pepsico Inc.', 'PEP'))
    insert_stock(Stock('Qualcomm Inc', 'QCOM'))
    insert_stock(Stock('Oracle Corp', 'ORCL'))
    insert_stock(Stock('Thermo Fisher, Inc.', 'TMO'))
    insert_stock(Stock('Linde Plc', 'LIN'))
    insert_stock(Stock('Wells Fargo & Co', 'WFC'))
    insert_stock(Stock('Applied Materials', 'AMAT'))
    insert_stock(Stock('Accenture Plc', 'ACN'))
    insert_stock(Stock('Cisco Systems Inc.', 'CSCO'))
    insert_stock(Stock('Walt Disney Company', 'DIS'))
    insert_stock(Stock('Mcdonald\'s Corp', 'MCD'))
    insert_stock(Stock('Abbott Laboratories', 'ABT'))
    insert_stock(Stock('Intuit Inc.', 'INTU'))
    insert_stock(Stock('Texas Instruments', 'TXN'))
    insert_stock(Stock('General Electric', 'GE'))
    insert_stock(Stock('Verizon Comm.', 'VZ'))
    insert_stock(Stock('Amgen Inc', 'AMGN'))
    insert_stock(Stock('Danaher Corp', 'DHR'))
    insert_stock(Stock('Caterpillar Inc.', 'CAT'))
    insert_stock(Stock('Philip Morris Int.', 'PM'))

    insert_news_source(Source(DUMMY_SOURCE_STRING, ' '))
    insert_news_source(Source('Forbes', 'www.forbes.com'))
    insert_news_source(Source('Nasdaq', 'www.nasdaq.com'))
    insert_news_source(Source('Yahoo ModuleFinance', 'finance.yahoo.com'))
    insert_news_source(Source('Investor Place', 'investorplace.com'))
    insert_news_source(Source('The Motley Fool', 'fool.com'))
    insert_news_source(Source('Investing.com', 'investing.com'))


if __name__ == '__main__':
    db_setup()
