@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class news_source {
   name: varchar(64)
   url: varchar(128)
   news_source_id: integer
}
class stock {
   name: varchar(20)
   ticker_symbol: varchar(5)
   stock_id: integer
}
class stock_news {
   stock_id: integer
   news_source_id: integer
   url: text
   source_url: text
   sentiment_exists: boolean
   sentiment: numeric
   ticker_related: boolean
   title: text
   description: text
   timeout_cnt: integer
   stock_news_id: bigint
   pub_date: timestamp with time zone
}
class stock_price {
   stock_price_id: bigint
   stock_price_val: numeric
   stock_id: integer
   stock_price_time: timestamp with time zone
}

stock_news   -[#595959,plain]-^  news_source : "news_source_id"
stock_news   -[#595959,plain]-^  stock       : "stock_id"
stock_price  -[#595959,plain]-^  stock       : "stock_id"
@enduml
