from Database import insert_stock, insert_news_source, DUMMY_SOURCE_STRING
from Source import Source
from Stock import Stock


def db_setup():
    insert_stock(Stock('Apple Inc.', 'AAPL'))
    insert_stock(Stock('Nvidia Corp', 'NVDA'))
    insert_stock(Stock('AMD', 'AMD'))
    insert_stock(Stock('Amazon.com Inc', 'AMZN'))
    insert_stock(Stock('Microsoft Corp', 'MSFT'))
    insert_stock(Stock('Meta Class A', 'META'))
    insert_stock(Stock('Alphabet Class A', 'GOOGL'))
    insert_stock(Stock('Alphabet Class C', 'GOOG'))
    insert_stock(Stock('Berkshire Hathaway', 'BRK-A'))
    insert_stock(Stock('Eli Lilly & Co', 'LLY'))
    insert_stock(Stock('Broadcom Inc.', 'AVGO'))
    insert_stock(Stock('Jpmorgan Chase & Co.', 'JPM'))
    insert_stock(Stock('Tesla, Inc.', 'TSLA'))
    insert_stock(Stock('Exxon Mobil Corp', 'XOM'))
    insert_stock(Stock('Unitedhealth Group', 'UNH'))
    insert_stock(Stock('Visa Inc.', 'V'))
    insert_stock(Stock('Procter & Gamble', 'PG'))
    insert_stock(Stock('Costco Wholesale', 'COST'))
    insert_stock(Stock('Mastercard Inc.', 'MA'))
    insert_stock(Stock('Johnson & Johnson', 'JNJ'))
    insert_stock(Stock('Merck & Co', 'MRK'))
    insert_stock(Stock('Home Depot, Inc.', 'HD'))
    insert_stock(Stock('Abbvie Inc.', 'ABBV'))
    insert_stock(Stock('Netflix Inc', 'NFLX'))
    insert_stock(Stock('Walmart Inc.', 'WMT'))
    insert_stock(Stock('Chevron Corp', 'CVX'))
    insert_stock(Stock('Bank of America Corp', 'BAC'))
    insert_stock(Stock('Coca-Cola Company', 'KO'))
    insert_stock(Stock('Adobe Inc.', 'ADBE'))
    insert_stock(Stock('Salesforce Inc.', 'CRM'))
    insert_stock(Stock('Pepsico Inc.', 'PEP'))
    insert_stock(Stock('Qualcomm Inc', 'QCOM'))
    insert_stock(Stock('Oracle Corp', 'ORCL'))
    insert_stock(Stock('Thermo Fisher, Inc.', 'TMO'))
    insert_stock(Stock('Linde Plc', 'LIN'))
    insert_stock(Stock('Wells Fargo & Co', 'WFC'))
    insert_stock(Stock('Applied Materials', 'AMAT'))
    insert_stock(Stock('Accenture Plc', 'ACN'))
    insert_stock(Stock('Cisco Systems Inc.', 'CSCO'))
    insert_stock(Stock('Walt Disney Company', 'DIS'))
    insert_stock(Stock('Mcdonald\'s Corp', 'MCD'))
    insert_stock(Stock('Abbott Laboratories', 'ABT'))
    insert_stock(Stock('Intuit Inc.', 'INTU'))
    insert_stock(Stock('Texas Instruments', 'TXN'))
    insert_stock(Stock('General Electric', 'GE'))
    insert_stock(Stock('Verizon Comm.', 'VZ'))
    insert_stock(Stock('Amgen Inc', 'AMGN'))
    insert_stock(Stock('Danaher Corp', 'DHR'))
    insert_stock(Stock('Caterpillar Inc.', 'CAT'))
    insert_stock(Stock('Servicenow, Inc.', 'NOW'))
    insert_stock(Stock('Intuitive Surgical', 'ISRG'))
    insert_stock(Stock('Pfizer Inc.', 'PFE'))
    insert_stock(Stock('IBM', 'IBM'))
    insert_stock(Stock('Nextra Energy, Inc.', 'NEE'))
    insert_stock(Stock('Comcast Corp', 'CMCSA'))
    insert_stock(Stock('Uber Technologies', 'UBER'))
    insert_stock(Stock('Micron Technology', 'MU'))
    insert_stock(Stock('Philip Morris Int.', 'PM'))
    insert_stock(Stock('Goldman Sachs Group', 'GS'))
    insert_stock(Stock('S&p Global Inc.', 'SPGI'))
    insert_stock(Stock('Honeywell Int., Inc.', 'HON'))
    insert_stock(Stock('Lam Research Corp', 'LRCX'))
    insert_stock(Stock('Union Pacific Corp.', 'UNP'))
    insert_stock(Stock('Booking Holdings Inc', 'BKNG'))
    insert_stock(Stock('At&t Inc.', 'T'))
    insert_stock(Stock('Rtx Corporation', 'RTX'))
    insert_stock(Stock('Conocophillips', 'COP'))
    insert_stock(Stock('American Express', 'AXP'))
    insert_stock(Stock('Intel Corp', 'INTC'))
    insert_stock(Stock('Lowe\'s Companies', 'LOW'))
    insert_stock(Stock('Eaton Corporation', 'ETN'))
    insert_stock(Stock('Tjx Companies, Inc.', 'TJX'))
    insert_stock(Stock('Elevance Health, Inc', 'ELV'))
    insert_stock(Stock('Progressive Corp.', 'PGR'))
    insert_stock(Stock('Vertex Pharma. Inc', 'VRTX'))
    insert_stock(Stock('Morgan Stanley', 'MS'))
    insert_stock(Stock('Citigroup Inc.', 'C'))
    insert_stock(Stock('Stryker Corporation', 'SYK'))
    insert_stock(Stock('Nike, Inc.', 'NKE'))
    insert_stock(Stock('Analog Devices, Inc', 'ADI'))
    insert_stock(Stock('Regeneron Pharma Inc', 'REGN'))
    insert_stock(Stock('Palo Alto Networks', 'PANW'))
    insert_stock(Stock('Kla Corporation', 'KLAC'))
    insert_stock(Stock('Charles Schwab Corp.', 'SCHW'))
    insert_stock(Stock('Blackrock, Inc.', 'BLK'))
    insert_stock(Stock('Chubb Limited', 'CB'))
    insert_stock(Stock('Boeing Company', 'BA'))
    insert_stock(Stock('Medtronic Plc', 'MDT'))
    insert_stock(Stock('Marsh & Mclennan', 'MMC'))
    insert_stock(Stock('Prologis, Inc.', 'PLD'))
    insert_stock(Stock('Lockheed Martin', 'LMT'))
    insert_stock(Stock('UPS Class B', 'UPS'))
    insert_stock(Stock('Deere & Company', 'DE'))
    insert_stock(Stock('ADP', 'ADP'))
    insert_stock(Stock('Cigna Group', 'CI'))
    insert_stock(Stock('T-Mobile Us', 'TMUS'))
    insert_stock(Stock('American Tower Corp.', 'AMT'))
    insert_stock(Stock('Synopsys Inc', 'SNPS'))
    insert_stock(Stock('Starbucks Corp', 'SBUX'))
    insert_stock(Stock('Crowdstrike Class A', 'CRWD'))

    insert_news_source(Source(DUMMY_SOURCE_STRING, ' '))
    insert_news_source(Source('Forbes', 'www.forbes.com'))
    insert_news_source(Source('Nasdaq', 'www.nasdaq.com'))
    insert_news_source(Source('Yahoo Finance', 'finance.yahoo.com'))
    insert_news_source(Source('Investor Place', 'investorplace.com'))
    # insert_news_source(Source('Seeking Alpha', 'seekingalpha.com'))
