services:
    postgres:
        restart: unless-stopped
        image: postgres:alpine
        ports:
        - 5432:5432
        volumes:
        - pgdata:/data/postgres
        - ./database/init:/docker-entrypoint-initdb.d
        env_file:
        - .env
        healthcheck:
            test:  pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
            interval: 5s
            timeout: 5s
            retries: 5
    webcrawler:
        build: ./webscraper
        env_file:
        - .env
        depends_on:
            postgres:
                condition: service_healthy
volumes:
    pgdata: